name: Jest Test

on:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  install:
    name: Install and Test

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Install
      run:  npm ci
    
    - name: Test with Jest
      run: npm test 