name: TLighthouse Setup and Test

on:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches: [main, development, dev-workflows]

jobs:
  install-ubuntu:
    name: Install TLighthouse
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run:  npm ci

  test-ubuntu:
    name: Test TLighthouse
    needs: install-ubuntu
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
  
      - name: Install Dependencies
        run:  npm ci
      
      - name: Testing with Jest
        run: npm test 

  running-ubuntu:
    name: Run TLighthouse
    needs: test-ubuntu
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run:  npm ci
    
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Running the program
      run: npm start 